# -*- coding: utf-8 -*-
"""DA-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJjUFH4uEi8lWxSQ2DFuzjxRCG6GHO5E
"""

# IMPORTS

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# DATASET DOWNLAOD

import kagglehub

# Download latest version
path = kagglehub.dataset_download("muhammadahmaddaar/mobile-price-classification")

print("Path to dataset files:", path)

print("First 5 rows of test.csv:")
display(data.head())

print("\nInformation about test.csv:")
print(data.info())

print("\nDescriptive statistics for test.csv:")
display(data.describe())

# DATASET FULL PREVIEW

import os
import pandas as pd

# Load the data from test.csv into a pandas DataFrame
data = pd.read_csv(os.path.join(path, 'test.csv'))

display(data)

# Step 3: Feature Selection
from sklearn.feature_selection import SelectKBest, chi2

data['battery_power_range'] = pd.cut(
    data['battery_power'],
    bins=4,
    labels=[0, 1, 2, 3]
).astype(int)

# Separate features and the new binned target
X = data.drop(columns=['id', 'battery_power', 'battery_power_range'])
y = data['battery_power_range']

# Select top 10 features using chi-squared test
selector = SelectKBest(score_func=chi2, k=10)
X_new = selector.fit_transform(X, y)

# Get selected feature names
selected_features = X.columns[selector.get_support()]
print("Top 10 features:", list(selected_features))

# Step 4: Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X[selected_features], y, test_size=0.2, random_state=42, stratify=y
)

# Step 5: Scale Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 6: Train Model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

# Step 7: Evaluate Model
y_pred = model.predict(X_test_scaled)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Confusion Matrix
plt.figure(figsize=(6,5))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# Step 8: Feature Importance
importances = model.feature_importances_
feat_importance = pd.Series(importances, index=selected_features).sort_values(ascending=False)

plt.figure(figsize=(8,6))
sns.barplot(x=feat_importance, y=feat_importance.index)
plt.title("Feature Importance")
plt.show()